name: build and deploy serverless application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: EnvSetup
      run: |
        touch .env
        echo TENCENT_SECRET_ID=${{secrets.TENCENT_SECRET_ID}} >> .env
        echo TENCENT_SECRET_KEY=${{secrets.TENCENT_SECRET_KEY}} >> .env
